#!/bin/bash
# Auto-generate .env on first boot if missing or has placeholder values.
# Run: bash generate_env.sh
set -euo pipefail

ENV_FILE=".env"

if [ -f "$ENV_FILE" ] && ! grep -q "change-me" "$ENV_FILE" 2>/dev/null; then
  echo "[generate_env] .env already configured, skipping."
  exit 0
fi

echo "[generate_env] Generating .env with secure secrets..."

SECRET_KEY=$(openssl rand -hex 32)
JWT_SECRET=$(openssl rand -hex 32)
POSTGRES_PASS=$(openssl rand -hex 16)
FLOWER_PASS=$(openssl rand -hex 12)

cat > "$ENV_FILE" << ENVEOF
# ─── Auto-generated by generate_env.sh ─────────────────────────────────────
APP_NAME=Vitar
ENVIRONMENT=production
SECRET_KEY=${SECRET_KEY}
DEBUG=false

# Domain — update ALLOWED_ORIGINS / ALLOWED_HOSTS / FRONTEND_URL before going live
# ALLOWED_ORIGINS set below for livevault.cloud

# Database
POSTGRES_PASSWORD=${POSTGRES_PASS}
DATABASE_URL=postgresql://vitar:${POSTGRES_PASS}@postgres:5432/vitar

# Redis / Celery
REDIS_URL=redis://redis:6379/0
CELERY_BROKER_URL=redis://redis:6379/1
CELERY_RESULT_BACKEND=redis://redis:6379/2

# Auth
JWT_SECRET_KEY=${JWT_SECRET}
ACCESS_TOKEN_EXPIRE_MINUTES=60
REFRESH_TOKEN_EXPIRE_DAYS=30

# CORS
ALLOWED_ORIGINS=["https://livevault.cloud","https://www.livevault.cloud","https://app.livevault.cloud","https://api.livevault.cloud"]
ALLOWED_HOSTS=["livevault.cloud","www.livevault.cloud","app.livevault.cloud","api.livevault.cloud"]

# Frontend
FRONTEND_URL=https://livevault.cloud
VITE_API_URL=https://livevault.cloud/api/v1
API_DOCS_ENABLED=true

# Trial limits
TRIAL_DAYS=14
TRIAL_MAX_BOOKINGS=50
TRIAL_MAX_DOCTORS=2

# Flower monitoring
FLOWER_USER=admin
FLOWER_PASSWORD=${FLOWER_PASS}

# ─── External services (fill in to enable) ─────────────────────────────────
PAYSTACK_SECRET_KEY=
PAYSTACK_PUBLIC_KEY=
PAYSTACK_WEBHOOK_SECRET=
STRIPE_SECRET_KEY=
STRIPE_PUBLISHABLE_KEY=
STRIPE_WEBHOOK_SECRET=
FLUTTERWAVE_SECRET_KEY=
FLUTTERWAVE_PUBLIC_KEY=
TERMII_API_KEY=
TERMII_SENDER_ID=Vitar
TWILIO_ACCOUNT_SID=
TWILIO_AUTH_TOKEN=
TWILIO_FROM_NUMBER=
WHATSAPP_PHONE_NUMBER_ID=
WHATSAPP_ACCESS_TOKEN=
SENDGRID_API_KEY=
EMAIL_FROM=no-reply@livevault.cloud
EMAIL_FROM_NAME=Vitar Health
GROQ_API_KEY=
SENTRY_DSN=
IPAPI_KEY=
EXCHANGE_RATE_API_KEY=
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_S3_BUCKET=vitar-uploads
AWS_REGION=us-east-1
STORAGE_BACKEND=local
ALLOW_LOCAL_UPLOADS_IN_PRODUCTION=true
UPLOAD_DIR=/app/uploads
DATABASE_POOL_SIZE=5
DATABASE_MAX_OVERFLOW=10
ENVEOF

echo "[generate_env] .env written. Secrets generated:"
echo "  POSTGRES_PASSWORD: ${POSTGRES_PASS}"
echo "  FLOWER_PASSWORD:   ${FLOWER_PASS}"
echo ""
echo "[generate_env] Done. You can now run: docker-compose up -d"
