#!/usr/bin/env bash
# =============================================================================
# Vitar v11 — First-Run Setup Script
# =============================================================================
# Usage:
#   chmod +x setup.sh
#   ./setup.sh           # interactive setup
#   ./setup.sh --dev     # dev mode: skips secret prompts, uses safe defaults
#   ./setup.sh --ci      # CI mode: non-interactive, assumes .env already exists
# =============================================================================
set -euo pipefail

MODE="interactive"
[[ "${1:-}" == "--dev" ]] && MODE="dev"
[[ "${1:-}" == "--ci"  ]] && MODE="ci"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
info()    { echo -e "${BLUE}[setup]${NC} $*"; }
success() { echo -e "${GREEN}[setup]${NC} $*"; }
warn()    { echo -e "${YELLOW}[setup]${NC} $*"; }
error()   { echo -e "${RED}[setup]${NC} $*" >&2; exit 1; }

# ── Prerequisites ─────────────────────────────────────────────────────────────
check_dep() {
    command -v "$1" &>/dev/null || error "$1 is required but not installed."
}
check_dep docker
check_dep docker-compose || check_dep "docker compose"
info "Prerequisites OK"

# ── .env setup ────────────────────────────────────────────────────────────────
if [[ "$MODE" == "ci" ]]; then
    [[ -f .env ]] || error ".env file not found (required in --ci mode)"
    info "CI mode: using existing .env"
else
    if [[ ! -f .env ]]; then
        info "Creating .env from .env.example ..."
        cp .env.example .env

        # Auto-generate strong secrets
        SECRET_KEY=$(openssl rand -hex 32 2>/dev/null || python3 -c "import secrets; print(secrets.token_hex(32))")
        JWT_SECRET=$(openssl rand -hex 32 2>/dev/null || python3 -c "import secrets; print(secrets.token_hex(32))")
        POSTGRES_PW=$(openssl rand -hex 16 2>/dev/null || python3 -c "import secrets; print(secrets.token_hex(16))")

        # Patch secrets into .env
        sed -i.bak \
            -e "s|SECRET_KEY=change-me-in-production-use-32-char-min|SECRET_KEY=${SECRET_KEY}|" \
            -e "s|JWT_SECRET_KEY=jwt-secret-change-in-production|JWT_SECRET_KEY=${JWT_SECRET}|" \
            .env
        rm -f .env.bak

        # Patch DATABASE_URL with generated password
        sed -i.bak \
            -e "s|DATABASE_URL=postgresql://vitar:vitar@|DATABASE_URL=postgresql://vitar:${POSTGRES_PW}@|" \
            .env
        rm -f .env.bak

        # Also write POSTGRES_PASSWORD for docker-compose
        echo "" >> .env
        echo "# Auto-generated by setup.sh — used by docker-compose postgres service" >> .env
        echo "POSTGRES_PASSWORD=${POSTGRES_PW}" >> .env

        success ".env created with auto-generated secrets"
    else
        warn ".env already exists — skipping creation (delete it to regenerate secrets)"
    fi
fi

# ── Create necessary local directories ────────────────────────────────────────
mkdir -p \
    infra/postgres/data \
    infra/redis/data \
    backend/uploads \
    backend/ml_models \
    /tmp/celery 2>/dev/null || true
info "Local directories created"

# ── Choose compose file ───────────────────────────────────────────────────────
COMPOSE_FILE="docker-compose.yml"
[[ "$MODE" == "dev" ]] && COMPOSE_FILE="docker-compose.dev.yml"

DC="docker compose"
command -v docker-compose &>/dev/null && DC="docker-compose"

# ── Pull / build ──────────────────────────────────────────────────────────────
info "Building images (this may take a few minutes on first run) ..."
$DC -f "$COMPOSE_FILE" build --parallel

# ── Start infrastructure first ────────────────────────────────────────────────
info "Starting infrastructure (postgres, redis) ..."
$DC -f "$COMPOSE_FILE" up -d postgres redis

# Wait for postgres
info "Waiting for Postgres to be ready ..."
MAX=30; COUNT=0
until $DC -f "$COMPOSE_FILE" exec -T postgres pg_isready -U vitar -q 2>/dev/null; do
    COUNT=$((COUNT+1))
    [[ $COUNT -ge $MAX ]] && error "Postgres did not become ready in time. Check logs: $DC logs postgres"
    sleep 2
done
success "Postgres is ready"

# Wait for redis
info "Waiting for Redis to be ready ..."
COUNT=0
until $DC -f "$COMPOSE_FILE" exec -T redis redis-cli ping 2>/dev/null | grep -q PONG; do
    COUNT=$((COUNT+1))
    [[ $COUNT -ge $MAX ]] && error "Redis did not become ready in time. Check logs: $DC logs redis"
    sleep 2
done
success "Redis is ready"

# ── Run database migrations ───────────────────────────────────────────────────
info "Running Alembic migrations ..."
$DC -f "$COMPOSE_FILE" run --rm api alembic upgrade head
success "Database migrations complete"

# ── Start all services ────────────────────────────────────────────────────────
info "Starting all services ..."
$DC -f "$COMPOSE_FILE" up -d

# ── Health check ──────────────────────────────────────────────────────────────
info "Waiting for API to be healthy ..."
COUNT=0; MAX=20
until curl -sf http://localhost:8000/health > /dev/null 2>&1; do
    COUNT=$((COUNT+1))
    [[ $COUNT -ge $MAX ]] && {
        warn "API health check timed out. Showing logs:"
        $DC -f "$COMPOSE_FILE" logs --tail=30 api
        exit 1
    }
    sleep 3
done

success "======================================================"
success "  Vitar is running!"
success "  API:      http://localhost:8000"
success "  API docs: http://localhost:8000/api/docs"
success "  Frontend: http://localhost:5173 (dev) or :80 (prod)"
success "  Flower:   http://localhost:5555"
success "  Grafana:  http://localhost:3000"
success "======================================================"
info "To stop:  $DC -f $COMPOSE_FILE down"
info "To logs:  $DC -f $COMPOSE_FILE logs -f api"
