#!/usr/bin/env bash
# Fetches Cloudflare's current edge IP ranges and writes an nginx include file
# so nginx trusts Cloudflare as a proxy and recovers the real visitor IP from
# the CF-Connecting-IP header. Run this once at setup, then via cron monthly
# (Cloudflare's ranges change occasionally).
set -euo pipefail

OUT="$(dirname "$0")/../nginx/cloudflare-ips.conf"
TMP="$(mktemp)"

{
  echo "# Auto-generated by scripts/update-cloudflare-ips.sh — do not edit by hand"
  echo "# Regenerate with: bash scripts/update-cloudflare-ips.sh"
  echo "# Source: https://www.cloudflare.com/ips-v4/ and /ips-v6/"
  echo ""
  for ip in $(curl -fsSL https://www.cloudflare.com/ips-v4/); do
    echo "set_real_ip_from ${ip};"
  done
  for ip in $(curl -fsSL https://www.cloudflare.com/ips-v6/); do
    echo "set_real_ip_from ${ip};"
  done
  echo ""
  echo "real_ip_header CF-Connecting-IP;"
  echo "real_ip_recursive on;"
} > "$TMP"

mv "$TMP" "$OUT"
echo "Wrote $(grep -c set_real_ip_from "$OUT") Cloudflare ranges to $OUT"
echo "Reload nginx to apply: docker compose exec nginx nginx -s reload"
